.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, CHANGELOG.md, README.md
resolves #10, resolves #13
- Add a changelog
- Add GitHub templates for issues and pull requests
- Improve clarity and brevity of the README
=> Issue templates changelog

.bumpversion.cfg, RELEASE.md, dbt/adapters/mysql/__version__.py, setup.py
=> Bump version 0.18.0rc3

CHANGELOG.md, dbt/adapters/mysql/relation.py
resolves #20
Support case-sensitive identifiers (schemas, tables/views, and columns).
=> Support case-sensitive identifiers (schemas, tables/views, and columns)

.bumpversion.cfg, CHANGELOG.md, dbt/adapters/mysql/__version__.py, setup.py
=> Bump version: 0.18.0rc3 → 0.18.0

RELEASE.md
resolves #30
Separate version bumping and PyPi packaging into different sections
=> Separate version bumping and PyPi packaging into different sections

setup.py
resolves #35
This PR merely bumps the dependency of dbt to v0.19.0rc1 (without any other changes).
Note: none of these checklist items were actually addressed. They are deferred to subsequent pull requests.
=> Bump dbt to v0.19.0rc1

.gitignore, CHANGELOG.md, README.md, test/README.md, test/integration/mysql-5.6-odbc.dbtspec, test/integration/mysql-5.7-odbc.dbtspec, test/integration/mysql-8.0-odbc.dbtspec
resolves #39
Integration tests for MySQL via dbt-adapter-tests
=> Integration tests

README.md
Make only 1 table to display which dbt features are supported per MySQL version
=> Make only 1 table to display which dbt features are supported per MySQL version

CHANGELOG.md, Pipfile, Pipfile.lock, test/README.md
resolves #52
- Use dbt v0.19.0
- Use pytest-dbt-adapter v4.0
=> Use dbt-adapter-tests v4.0 and dbt v0.19.0

Pipfile, Pipfile.lock
resolves #54
Bump version of bleach to 3.3.0 or later
=> Bump version of bleach to 3.3.0 or later

.bumpversion.cfg, .circleci/config.yml, CHANGELOG.md, dbt/adapters/mysql/__version__.py, dbt/adapters/mysql5/__version__.py, setup.py
Initial CircleCI project setup.
Bootstrapping the CI/CD process in CircleCI, so none of the following checklist items are resolved yet.
=> CircleCI project setup

CHANGELOG.md, dbt/include/mysql/macros/materializations/incremental/helpers.sql, dbt/include/mysql/macros/materializations/incremental/incremental.sql, dbt/include/mysql5/macros/materializations/incremental/helpers.sql, dbt/include/mysql5/macros/materializations/incremental/incremental.sql
=> Execute incremental upsert queries separately

.circleci/config.yml, CHANGELOG.md, test/README.md, test/integration/mysql-5.7.dbtspec, tox.ini
=> Integration tests for MySQL 5.7

.circleci/config.yml, CHANGELOG.md, test/integration/mariadb-10.5.dbtspec, tox.ini
=> Integration tests for MariaDB 10.5

dbt/adapters/mysql5/impl.py, dbt/adapters/mysql5/relation.py, dbt/include/mysql5/dbt_project.yml, dbt/include/mysql5/macros/materializations/incremental/incremental.sql
=> Use accurate and specific adapter names

CHANGELOG.md, requirements.txt, setup.py
=> Support dbt 0.19.2

setup.py
=> Find namespace packages

CHANGELOG.md, dbt/include/mariadb/macros/materializations/test/test.sql, dbt/include/mysql/macros/materializations/test/test.sql, dbt/include/mysql5/macros/materializations/test/test.sql, requirements-dev.txt, requirements.txt, setup.py
=> Support dbt v0.20.0

CHANGELOG.md, dbt/adapters/mariadb/connections.py, dbt/adapters/mysql/connections.py, dbt/adapters/mysql5/connections.py
=> Replace `get_status` with `get_response`

README.md, test/README.md, test/integration/mariadb-10.5.dbtspec, test/integration/mysql-5.6.dbtspec, test/integration/mysql-5.7.dbtspec, test/integration/mysql-8.0.dbtspec, test/mysql.dbtspec
=> Fishtown Analytics renamed to dbt Labs

CHANGELOG.md, requirements.txt, setup.py
=> Support dbt v0.20.1

CHANGELOG.md, requirements.txt, setup.py
=> Support dbt v0.20.2

CHANGELOG.md, dbt/adapters/mariadb/connections.py, dbt/adapters/mysql/connections.py, dbt/adapters/mysql5/connections.py, dbt/include/mariadb/macros/materializations/test/test.sql, dbt/include/mysql/macros/materializations/test/test.sql, dbt/include/mysql5/macros/materializations/test/test.sql, requirements.txt, setup.py
=> Support dbt v0.21.1

.bumpversion.cfg, .circleci/config.yml, CHANGELOG.md, MANIFEST.in, dbt/adapters/mariadb/__version__.py, dbt/adapters/mariadb/connections.py, dbt/adapters/mariadb/impl.py, dbt/adapters/mysql/__version__.py, dbt/adapters/mysql/connections.py, dbt/adapters/mysql/impl.py, dbt/adapters/mysql5/__version__.py, dbt/adapters/mysql5/connections.py, dbt/adapters/mysql5/impl.py, requirements-dev.txt, requirements.txt, setup.py, test/unit/utils.py, tox.ini
=> Support dbt v1.0

CHANGELOG.md, requirements.txt
resolves #100
Explicit support for [dbt Core v1.1](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.1)
=> dbt Core 1.1

CONTRIBUTING.rst, README.md, setup.py
=> Use `python -m pip` everywhere

README.md
resolves #115
include supported python versions
=> docs(readme): include supported python versions

.bumpversion.cfg, RELEASE.md, dbt/adapters/mariadb/__version__.py, dbt/adapters/mysql/__version__.py, dbt/adapters/mysql5/__version__.py, setup.py
resolves #128
Support dbt-core v1.1
=> Support dbt-core v1.1

.bumpversion.cfg, RELEASE.md, dbt/adapters/mariadb/__version__.py, dbt/adapters/mysql/__version__.py, dbt/adapters/mysql5/__version__.py, requirements-dev.txt, setup.py
=> Bump to 1.2.0a1

.bumpversion.cfg, CONTRIBUTING.rst, requirements.txt, setup.py, tests/README.md, tests/functional/adapter/test_basic.py, tox.ini
resolves #133
Upgrade to a more modern version of `setup.py` taken from [here](https://github.com/dbt-labs/dbt-redshift/blob/28d22bd8abf53882c7f4ddde6d4b611a5c924a9d/setup.py).
=> Upgrade `setup.py`

.pre-commit-config.yaml, CONTRIBUTING.rst, requirements-dev.txt
resolves #132
Install `pre-commit` hooks to detect issues prior to commit like linting, formatting, etc.
=> `pre-commit` hooks

dev-requirements.txt
Fixes CI test failures seen in #173
=> Pin jsonschema version to fix tests
